# Generated by Django 4.1.3 on 2022-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=None)),
                ('release_date', models.DateField()),
                ('lte_exists', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
